---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: asvignesh
  name: mipvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: mipv