apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: tetris
        image: santospardos/unir:tetris03
        ports:
        - containerPort: 80
