apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list","create"]