kind: Deployment
apiVersion: apps/v1
metadata:
  name: sampleweb
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
     containers:
     - name: sampleweb
       image: nikhilnidhi/samplewebapp
  