kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: services
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    application: frontend
  