apiVersion: v1
kind: Service 
metadata:
  name: eks-sample-linux-service-nlb
  namespace: eks-sample-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer  
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: eks-sample-linux-app
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port