apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: dev
  labels:
    app: usermgmt
spec:
  type: NodePort
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 31231 # we can drop it and k8s will allocate port randomly in a specific range
  # specify to which pods traffic will be forwarded based on the labels of a pod
  selector:
    app: usermgmt