apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: dev
type: Opaque
data:
  # we specify key-value pairs of sensitive info
  # where values are not stored in a raw format, but base64-encoded
  mysql-db-user: cm9vdA== # base64 encoded root
  mysql-db-password: ZGJwYXNzd29yZDEx
  mysql-db-hostname: bXlzcWw= # base64 encoded mysql value
  mysql-db-host: bXlzcWw=
  mysql-db-name: dXNlcm1nbXQ= # base64 encoded usermgmt value