apiVersion: v1
kind: Service 
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort # ClusterIp, # NodePort
  selector:
    app: nginx
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31280 # Node Port