apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev3
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-02ccf9aa8ee3bbb94 }
      us-east-1b: { id: subnet-0876c0a9598e863ef }
      us-east-1c: { id: subnet-039a3321c432caa53 }

nodeGroups:
  - name: worker-nodes
    labels: { role: workers }
    instanceType: t3.micro
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
