apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-demo
  region: us-east-1

vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-0f9677e8641995a5f }
      eu-north-1b: { id: subnet-090cd48a6c70b7075 }
      eu-north-1c: { id: subnet-0e40b66d38ee9a3dc }

iam: 
  serviceRoleARN: "arn:aws:iam::370144434774:role/LabRole"

